#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World" when queried
#++    at the root with a curl GET request.

apt-get update
apt-get install -y nginx

sudo mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World" | sudo tee /etc/nginx/html/index.html
sudo printf '%s\n' 'server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /etc/nginx/html;
    index       index.html index.html;
}
' | sudo tee /etc/nginx/sites-available/default


service nginx restart
