#!/usr/bin/env bash
# installs and configures HAproxy on lb-01

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
listen webapp 0.0.0.0:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 203503-web-01 34.229.184.14:80 check
	server 203503-web-02 54.162.234.135:80 check
EOF
sudo service haproxy start
