#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 193099-web-01 34.229.184.14:80 check\n\tserver 193099-web-02 54.162.234.135:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
