#!/usr/bin/env bash
# installs and configures HAproxy

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/hap
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
listen webapp 0.0.0.0:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 121887-web-01 34.229.184.14:80 check 
        server 121887-web-02 54.162.234.135:80 check
EOF
sudo service haproxy start
