#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

for ((num=1; num<100; num++))
do
    message=""
    if (( num % 3 == 0 )); then
        message+="Fizz"
    fi
    if (( num % 5 == 0 )); then
        message+="Buzz"
    fi
    if [[ -z "$message" ]]; then
        message="$num"
    fi
    echo "$message"
done