#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# set counter to 0
counter=0

# loop while counter is less than 10
while [ $counter -lt 10 ]
do
  # display "Best School"
  echo "Best School"

  # increment counter
  ((counter++))
done
