#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "不吉利" (bad luck in Chinese) for the 4th iteration, unless the most curious is 4
#   "发财啦" (good luck in Chinese) for the 8th iteration, unless the most curious is 8
#   "Best School" for all other iterations

most_curious=8
bad_luck_num=4
num=1

while (( num <= 10 )); do
  if (( num == bad_luck_num && most_curious != bad_luck_num )); then
    echo "不吉利"
  elif (( num == most_curious && most_curious == 8 )); then
    echo "发财啦"
  else
    echo "Best School"
  fi
  (( num++ ))
done  
