#!/usr/bin/env bash
# Displays the time for 12 hours and 59 times.
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  while [ $minute -le 59 ]
  do
    printf "%2d\n" "$minute"
    (( minute++ ))
  done
  minute=1
  (( hour++ ))
done
