#!/usr/bin/env bash
# Displays all active IPv4 addresses on the machine.

# Get a list of all network interfaces and their IP addresses
interfaces=$(ip -o -4 addr list | awk '{print $2 " " $4}')

# Loop over each interface and extract its IP address
for interface in $interfaces; do
  ip=$(echo "$interface" | cut -d' ' -f2)
  if [[ -n $ip ]]; then
    echo "$interface"
  fi
done
