#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
sed 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf | sudo tee /etc/nginx/nginx.conf.tmp
sudo mv /etc/nginx/nginx.conf.tmp /etc/nginx/nginx.conf
sed '/listen       80 default_server;/a listen       8080 default_server;' /etc/nginx/nginx.conf | sudo tee /etc/nginx/nginx.conf.tmp
sudo mv /etc/nginx/nginx.conf.tmp /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -n service nginx startsudo -n service nginx start
